### ISSUE TITLE
Review CSS Grid Layout Module Level 1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#11]
The APA WG needs CSS accessibility expertise on review of [CSS Grid Layout Module Level 1](https://www.w3.org/TR/css-grid-1/).

[APA tracking page for CSS Grid Layout Module Level 1](https://www.w3.org/WAI/APA/wiki/CSS_Grid_Layout_Module_Level_1).

**Comment by IanPouncey** [comment]
This went to CR on 9 May 2017, so needs a review fairly urgently. Volunteers needed.

**Comment by IanPouncey** [comment]
Current feeling from APA is that this will be handled by the [CSS Accessibility API Mappings](https://github.com/w3c/css-aam).

The primary concern is how this affects content and focus order with AT and keyboards.

Proposal is to write informative documentation for AAM to describe the expected / preferred behaviour.

**Comment by IanPouncey** [comment]
Reviewed. Beyond the concern over content and focus order, that is addressed in a section on "Reordering and Accessibility" there are no further concerns. As previously discussed, guidance on content order would be beneficial but is not required as part of this specification.
