### ISSUE TITLE
Review Web Animations

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#12]
The APA WG needs CSS accessibility expertise on review of [Web Animations](https://www.w3.org/TR/web-animations-1/).

[APA tracking page for Web Animations](https://www.w3.org/WAI/APA/wiki/Web_Animations).

**Comment by IanPouncey** [comment]
[Emailed public-css-a11y on subject](https://lists.w3.org/Archives/Public/public-css-a11y/2018Feb/0000.html) of a universal browser setting for preventing movement.

**Comment by digilou** [comment]
Brought to APA meeting. Agreed [Media Queries 5](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-reduced-motion) introduces `prefers-reduced-motion` which addresses some problems animation creates. Will be discussed at TPAC.

**Comment by digilou** [comment]
Concerns for animation accessibility have been quelled by Media Queries 5 progress.
