### ISSUE TITLE
Review CSS Logical Properties and Values Level 1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#15]
APA requests review of [CSS Logical Properties and Values Level 1](https://www.w3.org/TR/css-logical-1/) which may relate to personalization.

**Comment by michael-n-cooper** [comment]
[APA tracking for this review](https://www.w3.org/WAI/APA/wiki/CSS_Logical_Properties_and_Values_Level_1)

**Comment by digilou** [comment]
@michael-n-cooper @IanPouncey
This draft spec doesn’t have any accessibility conflicts that I can determine. If anything, I could see how this could actually benefit assistive tech, especially cross-culturally. I’d recommend we close this issue.

**Comment by digilou** [comment]
APA consensus on 2020-11-11 this can be closed since review happened with no conflicts.
