### ISSUE TITLE
Review CSS Scroll Snap Module Level 1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#18]
[CSS Scroll Snap Module Level 1](https://www.w3.org/TR/css-scroll-snap-1/) needs accessibility review.

[APA tracking for this review](https://www.w3.org/WAI/APA/wiki/CSS_Scroll_Snap_Module_Level_1)

**Comment by IanPouncey** [comment]
Has been at CR since 09 February 2017, review needed ASAP.

**Comment by IanPouncey** [comment]
Reviewed, includes no accessibility specific issues in my opinion.
