### ISSUE TITLE
Review CSS Transforms Module Level 1

### ISSUE THREAD

**Issue by IanPouncey** [w3c/css-a11y#19]
The APA needs an accessibility review of [CSS Transforms Module Level 1
 1](https://www.w3.org/TR/css-transforms-1/).

**Comment by IanPouncey** [comment]
[Emailed public-css-a11y on subject](https://lists.w3.org/Archives/Public/public-css-a11y/2018Feb/0000.html) of a universal browser setting for preventing movement.

**Comment by digilou** [comment]
APA agreed that this has been overcome by events. Media Queries 5 is addressing issues like this. Additionally, CSS Transforms Module 2 is ready for review (#40).
