### ISSUE TITLE
Investigate the need for a ScrollView or Scrollable Region Property in ARIA 2.0

### ISSUE THREAD

**Issue by jnurthen** [w3c/css-a11y#22]
https://www.w3.org/WAI/ARIA/track/issues/340

> There has been some discussion of the need for a scrollbar and/or scrollview roles for ARIA 2.0, so we should investigate the need for a ScrollView or Scrollable Region Property in ARIA 2.0. This page be achieved by a property ('page in set' similar to 'pos in set') or by a new role, etc. The idea would be to allow AT to change the view in larger sets than just one at a time.

**Comment by digilou** [comment]
@jnurthen @joanmarie To keep this issue open, would you like to move this over to ARIA repo? Since the CSS A11y TF is fading away, the idea is that this repo will eventually fade too, but we don't want to lose ideas and threads that still need to be addressed.

**Comment by jnurthen** [comment]
Sounds really similar to https://github.com/w3c/aria/issues/1141 - I'm closing this based on that issue. If you think this is not covered then please add the required information to that issue.
