### ISSUE TITLE
display:contents breaks accessibility

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#24]
[An issue was filed against Bikeshed](https://github.com/tabatkins/bikeshed/issues/1316) saying use of display:contents breaks accessibility. It appears when this property is used, elements are not exposed to the accessibility API, leading to unexpected results particularly for containers and lists. Some user agent implementation guidance may be needed or consequences of this property further explored.

**Comment by michael-n-cooper** [comment]
See #7

**Comment by jonnyjames** [comment]
The `display: contents;` recommendation is addressed here [#3040](https://github.com/w3c/csswg-drafts/issues/3040)

**Comment by IanPouncey** [comment]
This has been raised with the CSS WG, closing this issue.
