### ISSUE TITLE
Review Geometry Interfaces Module Level 1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#31]
Review [Geometry Interfaces Module Level 1](https://www.w3.org/TR/geometry-1/). [APA Tracking for Geometry Interfaces Module Level 1](https://www.w3.org/WAI/APA/wiki/Geometry_Interfaces_Module_Level_1). Could have an issue of creating rendering of meaningful content that isn't otherwise exposed to the a11y tree. Might want an accessibility impact statement.

**Comment by digilou** [comment]
APA signed off on this on 16 Dec 2020 due to no action and no immediate issues identified.
