### ISSUE TITLE
Potential need for a new CSS pseudo-class for role matching

### ISSUE THREAD

**Issue by jnurthen** [w3c/css-a11y#32]
_From @therealglazou on December 29, 2016 11:39_

Testing in CSS an `epub:type` fallback for an absent `role` attribute is a bit cumbersome. Such a selector would be in the form of (for a cell role):

```
[epub|type="cell"]:not([role]) {
   ...
}
```

and it would require a namespace at-rule:

```
@namespace epub "http://www.idpf.org/2007/ops";
```
Maybe a new `:role()` pseudo-class is needed here to ease the pain and deal automagically with that fallback; some UAs could look only at `role` to resolve it while EPUB Agents would also deal with the `epub:type` fallback. Just thinking out loud here.... That would of course require joint work with the CSS WG.

_Copied from original issue: w3c/aria#506_

**Comment by jnurthen** [comment]
_From @AmeliaBR on December 29, 2016 15:41_

There is definitely a need for an API to access the computed role of an element.  The `role` itself can have fallback values, and values that are dis-allowed because of native semantics, and of course default roles based on semantics.  A CSS pseudo-class has the benefit of exposing this information to both scripts and declarative styling.

**Comment by jnurthen** [comment]
@IanPouncey something for the CSS Accessibility Task Force to consider?

**Comment by digilou** [comment]
APA has created an issue for the CSS-WG to see where this conversation needs to go.

**Comment by astearns** [comment]
Please use this older issue for the csswg: https://github.com/w3c/csswg-drafts/issues/3596
