### ISSUE TITLE
CSS Color Module Level 4

### ISSUE THREAD

**Issue by IanPouncey** [w3c/css-a11y#34]
https://www.w3.org/TR/css-color-4/

**Comment by IanPouncey** [comment]
There are no concerns with this module.

Effort has been made to encourage accessible use of color by linking to SC 1.4.1 Use of Color

**Comment by svgeesus** [comment]
CSS Color 4 now has an [Accessibility Considerations](https://drafts.csswg.org/css-color-4/#a11y-sec) section.

In addition to the encouragement of SC 1.4.1 it also points out the encouragement for legible foreground/background combinations of system colors, and explains why a harder requirement (AA or AAA contrast) was considered but could not be mandated. Comments on that section are very welcome.

**Comment by digilou** [comment]
Request for update of Accessibility Considerations made. No further review of spec is needed.
