### ISSUE TITLE
Review CSS Overscroll Behavior Module Level 1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#37]
Review [CSS Overscroll Behavior Module Level 1](https://www.w3.org/TR/css-overscroll-1/).

[APA tracking page](https://www.w3.org/WAI/APA/wiki/CSS_Overscroll_Behavior_Module_Level_1)

**Comment by digilou** [comment]
APA expresses some concern for keyboard accessibility / keyboard trap, but has nothing definitive at this time. Since this is still a working draft, APA will keep an eye on its progress and any new developments.
