### ISSUE TITLE
Review CSS Animation Worklet API

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#38]
Review [CSS Animation Worklet API](https://www.w3.org/TR/css-animation-worklet-1/).

**Comment by michael-n-cooper** [comment]
This relates to #12 and it's possible the issues are all there, but the API should be reviewed in light of it.

**Comment by digilou** [comment]
Per APA discussion, might be resolved, thanks to the introduction of [Media Queries 5](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-reduced-motion) 'prefers-reduced-motion'. Will be discussed at TPAC.

**Comment by digilou** [comment]
Concerns for animation accessibility have been quelled by Media Queries 5 progress.
