### ISSUE TITLE
Review CSS Painting API

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#4]
The APA WG needs CSS accessibility expertise on review of [CSS Painting API Level 1](https://www.w3.org/tr/css-paint-api-1/).

Originally filed as APA [ACTION-2055](https://www.w3.org/WAI/APA/track/actions/2055).

[APA tracking page for CSS Painting API Level 1](https://www.w3.org/WAI/APA/wiki/CSS_Painting_API_Level_1).

**Comment by digilou** [comment]
This ticket was re-reviewed by APA on 5 August 2020. Painting API Level 1 has been a candidate recommendation since 9 August 2018. Low level spec with no concerns from APA.
