### ISSUE TITLE
Review CSS Transforms Module Level 2

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#40]
Review [CSS Transforms Module Level 2](https://www.w3.org/TR/css-transforms-2/). [APA tracking for CSS Transforms Module Level 2](https://www.w3.org/WAI/APA/wiki/CSS_Transforms_Module_Level_2). Also note [APA activity on CSS Transforms Module Level 1](https://www.w3.org/WAI/APA/wiki/CSS_Transforms_Module_Level_1).

**Comment by digilou** [comment]
No accessibility issues found or anticipated. Issue submitted to CSS-WG to add an Accessibility Considerations section.
