### ISSUE TITLE
For Review: CSS Conditional Rules Module Level 3

### ISSUE THREAD

**Issue by digilou** [w3c/css-a11y#42]
Per an email to APA:

CSS WG requests Accessibility review of [CSS Conditional Rules Module Level 3](https://drafts.csswg.org/css-conditional-3/)

This specification is used to add conditional tests for supported features (@supports) or for particular media (@media) to a stylesheet. 
So for example the same document can have different styling on screen and in print, or the stylesheet author can check that some new CSS property is actually supported before using it. This enhances the robustness of styling, especially when older browsers are still in use.

Because this is purely a CSS syntactic feature, we feel that the none of the "if" clauses in the [a11y FAST self-review questionnaire](https://w3c.github.io/apa/fast/checklist.html) seem pertinent.

Please raise any accessibility features by opening an issue in the [https://github.com/w3c/csswg-drafts/issuescsswg GitHub repo](https://github.com/w3c/csswg-drafts/issues):

The [specification has been at CR](https://www.w3.org/TR/css3-conditional/) since [2013](https://lists.w3.org/Archives/Member/chairs/2013JanMar/0130.html) but due to the long interval since that time, CSSWG is restarting wide review before publishing a Candidate Recommendation Snapshot.

There is a [list of changes](https://drafts.csswg.org/css-conditional-3/*changes) since the 2013 CR

The [specification is widely implemented](https://test.csswg.org/harness/results/css-conditional-3_dev/grouped/) and we expect to meet the CR exit requirements in the next few months.

Thanks!

--
Chris Lilley
@svgeesus
Technical Director @ W3C
W3C Strategy Team, Core Web Design
W3C Architecture & Technology Team, Core Web & Media

**Comment by svgeesus** [comment]
Great to hear. Thanks for your swift review!
