### ISSUE TITLE
A "minimum-font-contrast" rule to adjust background pixels

### ISSUE THREAD

**Issue by bkimmelSQSP** [w3c/css-a11y#43]
Apologies if this isn't precisely the right place to log this issue, but in short I think it would go a long way towards solving the 86% of websites with contrast failure issues if we had a CSS rule like
```
minimum-font-contrast: 4.5, 4px;
```
Where `4.5` is the "contrast level" as defined by WCAG (which I know isn't entirely non-controversial but play along) and `4px` is the radius behind edge-of-text pixels that are adjusted (either dodging or burning them) to achieve the minimum contrast (presumably from bottom of z-order to the top).

Here's an example (very rough) where I used the new paintApi to make a kind of thing like it: https://github.com/w3c/css-houdini-drafts/issues/1042

I think this would help alleviate contrast issues on the web because:
1) Developers would like it because it's easy to "set-and-forget" and know that your font will show up regardless of what background you put under it and how it reflows.
2) Designers would accept it because it does a "minimum" amount of damage to creative background assets as opposed to "big blocks for contrast" to keep the message readable.

Thank you for your work.

**Comment by digilou** [comment]
Thanks for your suggestion @bkimmelSQSP. This repo is slowly fading away, so we're not taking new issues here. However, this would be a great suggestion to submit to the [CSS Working Group ](https://github.com/w3c/csswg-drafts/issues) repo.
