### ISSUE TITLE
Review CSS Counter Styles Level 3

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#6]
The APA WG needs CSS accessibility expertise on review of [CSS Counter Styles Level 3](https://www.w3.org/TR/css-counter-styles-3/).

Originally filed as APA [ACTION-2070](https://www.w3.org/WAI/APA/track/actions/2070).

[APA tracking page for CSS Counter Styles Level 3](https://www.w3.org/WAI/APA/wiki/CSS_Counter_Styles_Level_3).

**Comment by michael-n-cooper** [comment]
The PFWG sent comments on this spec, and the CSS WG responded with questions. The ball is now in the APA WG court for the formal comment, but APA needs help from the CSS TF to address the questions.

**Comment by IanPouncey** [comment]
Unsure of the status of this. The original feedback can be found at https://lists.w3.org/Archives/Member/wai-liaison/2013Aug/0000.html, but I can't find the response from CSS WG that was, as far as I can tell, sent in November of 2014. @michael-n-cooper, can you help me track this response down? I'll then contact the editor to see if feedback is still welcome/required.

**Comment by IanPouncey** [comment]
This would benefit from review to ensure that concerns raised at https://lists.w3.org/Archives/Member/wai-liaison/2013Aug/0000.html are addressed.

**Comment by digilou** [comment]
Ticket review by APA. APA will bring up with CSS Joint TPAC meeting to see if, as a CF, this still needs review by CSS A11y TF.

**Comment by digilou** [comment]
2021-03-24: APA agreed this was outdated and no issues have come up.
