### ISSUE TITLE
Review CSS Display Module Level 3

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#7]
The APA WG needs CSS accessibility expertise on review of [CSS Display Module Level 3](https://www.w3.org/TR/css-display-3/).

Originally filed as APA [ACTION-2055](https://www.w3.org/WAI/APA/track/actions/2055).

[APA tracking page for CSS Display Module Level 3](https://www.w3.org/WAI/APA/wiki/CSS_Display_Module_Level_3).

**Comment by IanPouncey** [comment]
There were no concerns in the initial review (by @fredesch), I'll take this on to do a final check after which this issue can hopefully be closed.

**Comment by IanPouncey** [comment]
I concurr with @fredesch, no accessibility concerns with this module, closing this issue.
