### ISSUE TITLE
Review CSS Containment Module Level 1

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#8]
The APA WG needs CSS accessibility expertise on review of [CSS Containment Module Level 1](https://www.w3.org/TR/css-contain-1/).

Originally filed as APA [ACTION-2055](https://www.w3.org/WAI/APA/track/actions/2055).

[APA tracking page for CSS Containment Module Level 1](https://www.w3.org/WAI/APA/wiki/CSS_Containment_Module_Level_1).

**Comment by michael-n-cooper** [comment]
This spec is currently under wide review, could go to CR soon, so needs attention quickly.

**Comment by 7mary4** [comment]
@Thierryk: did you have previous comments about this module?

**Comment by thierryk** [comment]
@7mary4 please don't drag me in here, I told you what I think of this kind of property already...

> This enables heavy optimizations

Most devs can't optimize basic CSS but we think they need a tool for "*heavy optimizations*"?

> by user agents when used well.

A tool that needs to be "*used well*"?

For some reason, this reminds me of [`will-change`](http://cssmojo.com/the-dark-side-of-the-will-change-property/)

**Comment by IanPouncey** [comment]
This spec is now a Candidate Recommendation until 8 November 2017, so there is a deadline for feedback. As it is, rather embarrassingly, assigned to me I'll complete the review I started months ago and will provide an update to this ticket within a week.

**Comment by IanPouncey** [comment]
I found no apparent accessibility concerns with this module, closing this issue.
